### ISSUE TITLE
Help new users better

### ISSUE THREAD

**Issue by khinshankhan** [the-programmers-hangout/emacs#1]
Not everyone is after an evil config, but many are. Likewise, not everyone is going to have linux machine (maybe due to comfort, maybe due to work). Possibly consider making different directories for different configs and explaining it in the readme. Also, maybe link resources to get users going.

**Comment by Dreameh** [comment]
Instead of making different directories, why don't we just download it all, and then make a function which in turn people can add their respective keybind, theme and so forth and it will activate?

That in turn makes it much easier to handle than just sticking configs into different directories.

Here's a smol list of what options can be added:

- Windows / Linux / Mac
- Emacs / Evil Bindings
- doom emacs themes (just write the options somewhere)
- Helm / Ivy
- Swiper or some other choice.

and so forth, but let's not make it all too big, because we dont want your 2k lines to pour over into this one x)

**Comment by khinshankhan** [comment]
Okay so new consensus: we make the config more bare bones and have snippets (lines of codes, nothing like a yasnippets, or we could include some useful yasnippets too) of features in a diff folder. This way we provide more flexibility and we have DRY code in the repository only. Potentially snippets may reference other snippets or hold multiple packages. They should probably be thoroughly documented as well.
